### ISSUE TITLE
Color change button doesn't work in new more-info look introduced by HomeAssistant 2023.3.x

### ISSUE THREAD

**Issue by pejotigrek** [thomasloven/lovelace-more-info-card#23]
after the more-info page look was changed in 2023.3.x HomeAssistant version, only power on/off, effect selector and brightness slider works. pressing the palette-button [color change option the icon in the middle] does nothing.

![image](https://user-images.githubusercontent.com/10796588/224483617-4090d712-49d5-4d3c-a9f3-ff3f3bcf3944.png)

I tried clearing the cache, multiple restarts, multiple devices, nothing happened. the issue is active both on desktop [via Chrome browser, Windows and Chromebook devices] and mobile [Android via Chrome browser and via HA Companion App].

**Comment by adabelleleiram** [comment]
Same here

**Comment by trytocry** [comment]
same

**Comment by bkbartk** [comment]
I had this issue for a couple of cards,
in HA v 2023.4 I was able to replace them all by "Tile" cards

**Comment by DeFlanko** [comment]
What ended up working for me was:

```yaml
type: custom:slider-button-card
entity: light.office_bars
slider:
  direction: left-right
  background: gradient
  use_state_color: true
  use_percentage_bg_opacity: false
  show_track: false
  toggle_on_click: false
  force_square: false
show_name: true
show_state: true
compact: true
icon:
  show: true
  use_state_color: true
  tap_action:
    action: more-info
  icon: ''
action_button:
  mode: toggle
  icon: mdi:power
  show: true
  show_spinner: true
  tap_action:
    action: toggle
name: Office bars

```

![image](https://user-images.githubusercontent.com/5233969/233798596-44ad42ee-c7b4-482a-b5a4-04f550db994e.png)

![image](https://user-images.githubusercontent.com/5233969/233798653-ac400aab-d206-4814-b2b9-2f205790b226.png)
