### ISSUE TITLE
Card mod causes elements to be infinitely replicated

### ISSUE THREAD

**Issue by ScottG489** [thomasloven/lovelace-more-info-card#24]
Not sure if this is a bug in this card or `card_mod`, but with the reproduction step below, the light toggle at the top of the card (contained in the `state-card-content` element) will infinitely replicate. Obviously this is really dangerous and will eventually grind at least the users dashboard tab to a halt.

Minimal reproduction:
```yaml
type: custom:more-info-card
entity: light.kitchen_lights
card_mod:
  style:
    state-card-content:
```

It's a little finicky sometimes, but try saving it and reopening the editor and such.
