### ISSUE TITLE
Hide the attributes dropdown menu

### ISSUE THREAD

**Issue by justinbyoung** [thomasloven/lovelace-more-info-card#30]
Hi,

Is it possible to remove/hide the attributes dropdown menu that appears for some entities? I am hoping there is using card-mod but I have not been able to work it out myself.

e.g.
![Capture](https://github.com/thomasloven/lovelace-more-info-card/assets/27791449/d50dae89-4b56-48cb-9143-a3a77a0ebfdc)

**Comment by justinbyoung** [comment]
I found a workaround by creating a light group just containing that one light.

**Comment by conorlap** [comment]
+1 would like to be able to hide both the Attributes dropdown and the Effects button!

**Comment by RichieGP** [comment]
+1, I would like to remove attributes, the titles and the on/off toggle.  Any help would be much appreicated!  Is this something that is possible?  Thank you in advance if you are able to help

**Comment by cajusber** [comment]
The following works for me:

```yaml
type: horizontal-stack
grid_options:
  columns: full
cards:
  - type: custom:more-info-card
    entity: light.lightstrip
    title: My light
    card_mod:
      style:
        more-info-content: |
          state-card-content {
            display: none;
          }
        more-info-content$ more-info-light$ ha-attributes$: |
          ha-expansion-panel {
            display: none;
          }

```
